In [12]:
# importing the numpy package in to the project
#np.array sending the values of list to change it
import numpy as np
list = [1,2,3,]
np.array(list)

array([1, 2, 3])

In [15]:
list = [2,3,4,5]
np.array(list)

array([2, 3, 4, 5])

In [7]:
matrix = [[1,2,3],[4,5,6]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
matrix = [[2,3,4],[6,4,3],[5,7,9],[6,8,2]]
np.array(matrix)

array([[2, 3, 4],
       [6, 4, 3],
       [5, 7, 9],
       [6, 8, 2]])

In [18]:
#  range is defined as arange()  will give the range values from 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# arange of (0,10,2) will give the range values from 0 to 10 will difference of 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.arange(5,25,5)

array([ 5, 10, 15, 20])

In [25]:
np.arange(2,100,5)

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82,
       87, 92, 97])

In [27]:
np.arange(4,20,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# zeros method defined as zeros() and it  will create an array which consist of zeros
np.zeros(4)


array([0., 0., 0., 0.])

In [199]:
# zero given in range
np.zeros(1)

array([0.])

In [3]:
# to create a 4*4 matrix we should place two braces to create more than one dimension matrix we use double braces
import numpy as np
s = np.zeros((4,4))
s+=4
s

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [38]:
np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [201]:
# ones method defined as ones()  and used to dispaly one
np.ones(4)

array([1., 1., 1., 1.])

In [44]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
np.ones((6,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.ones((8,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [53]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [5]:
#linspace() method can take two or three arugments
#linspace()used to specifically split the range function it will split according to the last value mentioned
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [66]:
# it will split the range only once because we gave it to split only once
np.linspace(10,40,1)

array([10.])

In [64]:
#ill split the range only 5 times because we gave it to split only 5 times
np.linspace(30,50,5)

array([30., 35., 40., 45., 50.])

In [67]:
# it will split 15 times the range because we gave 15
np.linspace(80,90,15)

array([80.        , 80.71428571, 81.42857143, 82.14285714, 82.85714286,
       83.57142857, 84.28571429, 85.        , 85.71428571, 86.42857143,
       87.14285714, 87.85714286, 88.57142857, 89.28571429, 90.        ])

In [10]:
# identity  defined as eye()  and it is used to take an array as identity matrix
s = np.eye(4)
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [76]:
# random  defined rand() take values random which cant even predicted 
np.random.rand(5)

array([0.9520161 , 0.32939037, 0.04697484, 0.37408419, 0.62012662])

In [2]:
import numpy as np
np.random.rand(7)

array([0.39716712, 0.91864173, 0.53132273, 0.60876033, 0.84483707,
       0.47992556, 0.30497405])

In [11]:
# reshape
import numpy as np
b = np.arange(25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
# reshape
import numpy as np
b = np.arange(50).reshape(5,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [22]:
# reshape
import numpy as np
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
# reshape
import numpy as np
b = np.arange(100).reshape(10,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
# reshape
import numpy as np
b = np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [30]:
g = np.arange(12).reshape(3,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
f = np.random.randint(1,50)
f

11

In [23]:
g = np.random.randint(50,100,20)
g



array([86, 83, 76, 56, 66, 89, 94, 85, 66, 83, 84, 92, 50, 81, 73, 97, 96,
       96, 94, 97])

In [37]:
g = np.random.randint(10,20,100)
g

array([13, 12, 17, 16, 14, 18, 17, 16, 13, 15, 16, 18, 13, 12, 18, 14, 17,
       19, 11, 16, 14, 10, 12, 17, 18, 14, 13, 17, 16, 19, 10, 17, 19, 13,
       14, 12, 11, 12, 18, 14, 18, 18, 12, 15, 18, 10, 16, 16, 10, 11, 17,
       19, 14, 10, 10, 12, 14, 15, 18, 18, 15, 13, 14, 14, 19, 18, 11, 12,
       15, 17, 12, 10, 18, 19, 11, 15, 13, 14, 14, 10, 13, 11, 10, 10, 12,
       13, 11, 18, 14, 13, 17, 17, 13, 17, 18, 19, 13, 17, 15, 16])

In [52]:
g = np.random.randint(50,100)
g

90

In [57]:
# matrix addition @ used for adding
a = np.array([[2,3],[6,7]])
b = np.array([[6,8],[4,9]])
c = a @ b
c

array([[ 24,  43],
       [ 64, 111]])

In [68]:
a = np.array([[2,3,6],[6,7,8],[6,8,9]])
b = np.array([[6,8,2],[4,9,2],[5,9,3]])
c = a@b
c

array([[ 54,  97,  28],
       [104, 183,  50],
       [113, 201,  55]])

In [73]:
a = np.array([[2,3,6,8],[6,7,8,8],[6,8,9,8],[6,8,5,3]])
b = np.array([[6,8,2,5],[4,9,2,5],[5,9,3,3],[6,9,3,2]])
c = a@b
c

array([[102, 169,  52,  59],
       [152, 255,  74, 105],
       [161, 273,  79, 113],
       [111, 192,  52,  91]])

In [75]:
a = np.array([[2,3,6,8,1],[6,7,8,8,4],[6,8,9,8,7],[6,8,5,3,6],[2,3,4,5,6]])
b = np.array([[6,8,2,5,6],[4,9,2,5,3],[5,9,3,3,2],[6,9,3,2,1],[2,4,6,7,8]])
c = a@b
c

array([[104, 173,  58,  66,  49],
       [160, 271,  98, 133, 113],
       [175, 301, 121, 162, 142],
       [123, 216,  88, 133, 121],
       [ 86, 148,  73,  89,  82]])

In [122]:
# randint() used to choose an random int
s = np.random.randint(50,100,10)
s.max()

92

In [126]:
d = np.random.randint(7,40,1)
d.min()

29

In [135]:
s = np.random.randint(20,30,5)
s.min()
print(s.min())

20


In [151]:
c = np.random.randint(30,50,3)
c.min()

41

In [163]:
# matrix addition
c = np.array([[2,3,8],[7,8,8]])
d = np.array([[6,9,7],[4,3,9],[5,8,9]])
e = c@d
e

array([[ 64,  91, 113],
       [114, 151, 193]])

In [165]:
c = np.array([[1,2,3],[2,4,5],[5,6,7]])
d = np.array([[6,8,1],[6,5,7],[3,4,5]])
e = np.array([[5,7,7],[3,7,9],[6,0,4]])
f = c.dot(d).dot(e)
f

array([[ 405,  399,  579],
       [ 753,  749, 1081],
       [1221, 1295, 1819]])

In [167]:
c = np.array([[4,7,8],[7,9,4],[6,4,2]])
d = np.array([[7,8,4],[2,4,5],[1,9,4]])
e = c@d
e

array([[ 50, 132,  83],
       [ 71, 128,  89],
       [ 52,  82,  52]])

In [178]:
# getting out the matrix which we want by adding numbers to it
s = np.ones((2,2))
s+=4
s


array([[5., 5.],
       [5., 5.]])

In [190]:
# adding five to the zero matrix
s = np.zeros((4,4))
s+=5
s

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [193]:
# giving index to get particular value at index
a = np.arange(0,20)
print(a)
a[8]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


8

In [2]:
import numpy as np
s = np.arange(20,30)
print(s)
s[3]

[20 21 22 23 24 25 26 27 28 29]


23

In [8]:
s = np.ones((4,4))
s+=2
s
s1 = np.ones((4,4))
s1+=2
s1
s3 = s@s1
s3

array([[36., 36., 36., 36.],
       [36., 36., 36., 36.],
       [36., 36., 36., 36.],
       [36., 36., 36., 36.]])

In [5]:
import numpy as np
s1 = np.ones((5,5))
s2 = np.ones((5,5))
s3 = s1@s2
s3

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [11]:
# arithmetic operations addition
a = np.arange(30,40)
print(a)
a

[30 31 32 33 34 35 36 37 38 39]


array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [12]:
a = np.arange(0,10)
print(a)
a+a

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
s = np.arange(50,60)
print(s)
s-s

[50 51 52 53 54 55 56 57 58 59]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# subtraction
d = np.arange(40,90)
print(d)
d-d

[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87
 88 89]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [19]:
f = np.arange(10,40)
print(f)
f-f

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# multiplication
g = np.arange(90,150)
print(g)
g*g

[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]


array([ 8100,  8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,
        9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449,
       11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456,
       13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625,
       15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956,
       18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449,
       20736, 21025, 21316, 21609, 21904, 22201])

In [23]:
g = np.arange(30,50)
print(g)
g*g

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600,
       1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401])

In [25]:
# division
g = np.arange(90,150)
print(g)
g/g

[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
k = np.arange(0,50)
print(k)
k/k

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


C:\Users\Kotha Maheshwari\AppData\Local\Temp\ipykernel_9952\2112686530.py:3: RuntimeWarning: invalid value encountered in true_divide
  k/k


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [30]:
# square root
h = np.arange(30,60)
print(h)
np.sqrt(h)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]


array([5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575])

In [32]:
l = np.arange(10,20)
print(l)
np.sqrt(l)

[10 11 12 13 14 15 16 17 18 19]


array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [34]:
d = np.arange(30,40)
print(d)
np.sqrt(d)

[30 31 32 33 34 35 36 37 38 39]


array([5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ])

In [35]:
# exponential
f = np.arange(50,60)
print(f)
np.exp(f)

[50 51 52 53 54 55 56 57 58 59]


array([5.18470553e+21, 1.40934908e+22, 3.83100800e+22, 1.04137594e+23,
       2.83075330e+23, 7.69478527e+23, 2.09165950e+24, 5.68572000e+24,
       1.54553894e+25, 4.20121040e+25])

In [36]:
t = np.arange(30,40)
print(t)
np.exp(t)

[30 31 32 33 34 35 36 37 38 39]


array([1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14,
       5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
       3.18559318e+16, 8.65934004e+16])

In [37]:
e = np.arange(70,100)
print(e)
np.exp(e)

[70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93
 94 95 96 97 98 99]


array([2.51543867e+30, 6.83767123e+30, 1.85867175e+31, 5.05239363e+31,
       1.37338298e+32, 3.73324200e+32, 1.01480039e+33, 2.75851345e+33,
       7.49841700e+33, 2.03828107e+34, 5.54062238e+34, 1.50609731e+35,
       4.09399696e+35, 1.11286375e+36, 3.02507732e+36, 8.22301271e+36,
       2.23524660e+37, 6.07603023e+37, 1.65163625e+38, 4.48961282e+38,
       1.22040329e+39, 3.31740010e+39, 9.01762841e+39, 2.45124554e+40,
       6.66317622e+40, 1.81123908e+41, 4.92345829e+41, 1.33833472e+42,
       3.63797095e+42, 9.88903032e+42])

In [41]:
# minimum 
f = np.arange(40,60)
print(f)
np.min(f)

[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


40

In [43]:
b = np.arange(50,80)
print(b)
np.min(b)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79]


50

In [44]:
# maximum
g = np.arange(40,90)
print(g)
np.max(g)

[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87
 88 89]


89

In [45]:
s = np.arange(50,80)
print(s)
np.max(s)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79]


79

In [46]:
# log value
t = np.arange(20,50)
print(t)
np.log(t)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


array([2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ])

In [48]:
f = np.arange(50,80)
print(f)
np.log(f)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79]


array([3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
       4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744,
       4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
       4.17438727, 4.18965474, 4.20469262, 4.21950771, 4.2341065 ,
       4.24849524, 4.26267988, 4.27666612, 4.29045944, 4.30406509,
       4.31748811, 4.33073334, 4.34380542, 4.35670883, 4.36944785])

In [57]:
# indexing for matrix
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)
z[1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4, 5, 6])

In [59]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)
z[0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3])

In [61]:
# gives the value of 2nd row that is 7,8,9 where it is located at 2nd index
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)
z[2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [62]:
# z[0][1] gives the value of 0 row and 1st value
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)
z[0][1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [63]:
# gives the value of 1st  row that is 4,5,6 where it is located at 1st index and inner index is 2
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)
z[1][2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6

In [65]:
z = np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6],[1,3,8]])
print(z)
z[4]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]
 [1 3 8]]


array([1, 3, 8])

In [66]:
z = np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6],[1,3,8]])
print(z)
z[0][2]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]
 [1 3 8]]


3

In [67]:
z = np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6],[1,3,8]])
print(z)
z[1][0]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]
 [1 3 8]]


4

In [73]:
# slicing
s = ([[6,7,8],[5,4,3],[4,8,9],[2,3,4]])
print(s)
s[0:1]

[[6, 7, 8], [5, 4, 3], [4, 8, 9], [2, 3, 4]]


[[6, 7, 8]]

In [78]:
# slcing the index here [2:3] it takes only 2nd index values
s = ([[6,7,8],[5,4,3],[4,8,9],[2,3,4]])
print(s)
s[2:3]

[[6, 7, 8], [5, 4, 3], [4, 8, 9], [2, 3, 4]]


[[4, 8, 9]]

In [80]:
# slicing the index [2:] it takes from 2nd index value to the last
s = ([[6,7,8],[5,4,3],[4,8,9],[2,3,4]])
print(s)
s[2:]

[[6, 7, 8], [5, 4, 3], [4, 8, 9], [2, 3, 4]]


[[4, 8, 9], [2, 3, 4]]

In [83]:
# slicing the index it takes[0:] from index 0 to last
s = ([[6,7,8],[5,4,3],[4,8,9],[2,3,4]])
print(s)
s[0:]

[[6, 7, 8], [5, 4, 3], [4, 8, 9], [2, 3, 4]]


[[6, 7, 8], [5, 4, 3], [4, 8, 9], [2, 3, 4]]

In [89]:
# looping
l = np.zeros((10,10))
s = l.shape[1]
for i in range(s):
    l[i]=i
l

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [91]:
d = np.zeros((4,4))
e = d.shape[1]
for i in range(e):
    d[i]=i
d

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [2]:
import numpy as np
c = np.zeros((6,6))
d = c.shape[1]
for i in range(d):
    c[i]=i
c

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.]])

In [4]:
s = np.arange(12).reshape(3,4)
print(s)
for row in s:
    for column in row:
        print(column)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
d = np.arange(25).reshape(5,5)
print(d)
for row in d:
    for column in row:
        print(column)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [9]:
e = np.arange(16).reshape(4,4)
print(e)
for row in e:
    for column in row:
        print(column)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [12]:
# joining concatenate() will concatenate tha is kind of joining
s1 = np.array([[4,5],[8,9]])
s2 = np.array([[9,2],[4,5]])
s3 = np.concatenate((s1,s2),axis=1)
s3

array([[4, 5, 9, 2],
       [8, 9, 4, 5]])

In [16]:
e = np.array([[3,4],[6,7]])
h = np.array([[8,9],[2,2]])
d = np.concatenate((e,h),axis=0)
d

array([[3, 4],
       [6, 7],
       [8, 9],
       [2, 2]])

In [20]:
r1 = np.array([[3,4,5],[1,6,9],[4,9,1]])
r2 = np.array([[9,4,5],[2,6,7],[1,4,5]])
r3 = np.concatenate((r1,r2),axis=1)
r3

array([[3, 4, 5, 9, 4, 5],
       [1, 6, 9, 2, 6, 7],
       [4, 9, 1, 1, 4, 5]])

In [22]:
d1 = np.array([[1,3,6,1],[4,5,6,5],[8,9,1,9],[4,5,6,9]])
d2 = np.array([[6,7,2,3],[1,6,9,3],[6,1,7,3],[2,9,5,4]])
d3 = np.concatenate((d1,d2),axis=1)
d3

array([[1, 3, 6, 1, 6, 7, 2, 3],
       [4, 5, 6, 5, 1, 6, 9, 3],
       [8, 9, 1, 9, 6, 1, 7, 3],
       [4, 5, 6, 9, 2, 9, 5, 4]])

In [24]:
s1 = np.array([[1,3,6,1,5],[4,5,6,5,3],[8,9,1,9,2],[4,5,6,9,4]])
s2 = np.array([[6,7,2,3,2],[1,6,9,3,4],[6,1,7,3,2],[2,9,5,4,1]])
s3 = np.concatenate((s1,s2),axis=1)
s3

array([[1, 3, 6, 1, 5, 6, 7, 2, 3, 2],
       [4, 5, 6, 5, 3, 1, 6, 9, 3, 4],
       [8, 9, 1, 9, 2, 6, 1, 7, 3, 2],
       [4, 5, 6, 9, 4, 2, 9, 5, 4, 1]])

In [28]:
r1 = np.array([[2,3],[4,5]])
r2 = np.array([[7,8],[1,2]])
r3 = np.array([[4,6],[8,9]])
r4 = np.concatenate((r1,r2,r3),axis=1)
r4

array([[2, 3, 7, 8, 4, 6],
       [4, 5, 1, 2, 8, 9]])

In [30]:
d1 = np.array([[1,3,6,1],[4,5,6,5],[8,9,1,9],[4,5,6,9]])
d2 = np.array([[6,7,2,3],[1,6,9,3],[6,1,7,3],[2,9,5,4]])
d3 = np.array([[8,9,3,6],[2,4,7,4],[8,4,5,3],[3,8,9,2]])
d4 = np.concatenate((d1,d2,d3),axis=1)
d4

array([[1, 3, 6, 1, 6, 7, 2, 3, 8, 9, 3, 6],
       [4, 5, 6, 5, 1, 6, 9, 3, 2, 4, 7, 4],
       [8, 9, 1, 9, 6, 1, 7, 3, 8, 4, 5, 3],
       [4, 5, 6, 9, 2, 9, 5, 4, 3, 8, 9, 2]])

In [36]:
#spliting split() will split the array
s = np.array([[5,7],[5,8]])
np.split(s,1)
s


array([[5, 7],
       [5, 8]])

In [42]:
d = np.array([[4,5,7],[9,2,4],[3,7,1]])
np.split(d,3)
d

array([[4, 5, 7],
       [9, 2, 4],
       [3, 7, 1]])

In [57]:
e = np.array([[3,5,7,2],[5,8,9,4],[3,8,4,1],[8,1,2,3]])
np.split(e,2)
e

array([[3, 5, 7, 2],
       [5, 8, 9, 4],
       [3, 8, 4, 1],
       [8, 1, 2, 3]])

In [59]:
e = np.array([[3,5,7,2],[5,8,9,4],[3,8,4,1],[8,1,2,3]])
np.split(e,4)
e

array([[3, 5, 7, 2],
       [5, 8, 9, 4],
       [3, 8, 4, 1],
       [8, 1, 2, 3]])

In [63]:
r = np.array([[3,7,8,9,3,9,4],[7,9,3,2,8,9,5],[2,9,4,5,2,6,3],[6,1,1,3,4,6,4],[4,9,2,5,6,1,3],[2,1,4,5,6,2,1],[2,4,6,1,4,2,4]])
np.split(r,1)
r

array([[3, 7, 8, 9, 3, 9, 4],
       [7, 9, 3, 2, 8, 9, 5],
       [2, 9, 4, 5, 2, 6, 3],
       [6, 1, 1, 3, 4, 6, 4],
       [4, 9, 2, 5, 6, 1, 3],
       [2, 1, 4, 5, 6, 2, 1],
       [2, 4, 6, 1, 4, 2, 4]])

In [65]:
r = np.array([[3,7,8,9,3,9,4],[7,9,3,2,8,9,5],[2,9,4,5,2,6,3],[6,1,1,3,4,6,4],[4,9,2,5,6,1,3],[2,1,4,5,6,2,1],[2,4,6,1,4,2,4]])
np.split(r,7)
r

array([[3, 7, 8, 9, 3, 9, 4],
       [7, 9, 3, 2, 8, 9, 5],
       [2, 9, 4, 5, 2, 6, 3],
       [6, 1, 1, 3, 4, 6, 4],
       [4, 9, 2, 5, 6, 1, 3],
       [2, 1, 4, 5, 6, 2, 1],
       [2, 4, 6, 1, 4, 2, 4]])

In [69]:
r = np.array([[3,7,8,9,3,9,4],[7,9,3,2,8,9,5],[2,9,4,5,2,6,3],[6,1,1,3,4,6,4],[4,9,2,5,6,1,3],[2,1,4,5,6,2,1],[2,4,6,1,4,2,4]])
np.split(r,7)
r

array([[3, 7, 8, 9, 3, 9, 4],
       [7, 9, 3, 2, 8, 9, 5],
       [2, 9, 4, 5, 2, 6, 3],
       [6, 1, 1, 3, 4, 6, 4],
       [4, 9, 2, 5, 6, 1, 3],
       [2, 1, 4, 5, 6, 2, 1],
       [2, 4, 6, 1, 4, 2, 4]])

In [70]:
#sorting sort() will sort the values from small to big
d = np.array([[2,9,7],[3,5,9],[2,3,5]])
np.sort(d)

array([[2, 7, 9],
       [3, 5, 9],
       [2, 3, 5]])

In [71]:
g = np.array([[3,4,5,6],[7,2,4,1],[2,4,9,1],[4,8,7,6]])
np.sort(g)

array([[3, 4, 5, 6],
       [1, 2, 4, 7],
       [1, 2, 4, 9],
       [4, 6, 7, 8]])

In [73]:
d = np.array([[66,88,24],[50,87,77],[89,56,100]])
np.sort(d)

array([[ 24,  66,  88],
       [ 50,  77,  87],
       [ 56,  89, 100]])

In [74]:
f = np.array([[3,90,56],[78,65,900],[300,56,788]])
np.sort(f)

array([[  3,  56,  90],
       [ 65,  78, 900],
       [ 56, 300, 788]])

In [75]:
f = np.array([[56,78,34,43,27],[45,89,23,31,32],[67,34,56,43,21],[56,78,45,31,21],[67,90,45,34,21]])
np.sort(f)

array([[27, 34, 43, 56, 78],
       [23, 31, 32, 45, 89],
       [21, 34, 43, 56, 67],
       [21, 31, 45, 56, 78],
       [21, 34, 45, 67, 90]])

In [76]:
h = np.array([[34,21],[56,32]])
np.sort(h)

array([[21, 34],
       [32, 56]])

In [91]:
#flip() will flip the values that is last becomes first and first becomes last vice versa
f = np.array([3,4,5,6,7])
np.flip(f)

array([7, 6, 5, 4, 3])

In [93]:
d = np.array([[8,4,3],[3,5,1],[4,6,7]])
np.flip(d)

array([[7, 6, 4],
       [1, 5, 3],
       [3, 4, 8]])

In [95]:
e = np.array([[6,7,3,4],[5,3,2,1],[5,3,2,1],[3,5,6,7]])
np.flip(e)

array([[7, 6, 5, 3],
       [1, 2, 3, 5],
       [1, 2, 3, 5],
       [4, 3, 7, 6]])

In [97]:
h = np.array([[3,2],[6,7]])
np.flip(h)

array([[7, 6],
       [2, 3]])

In [99]:
u = np.array([[7,8,9,6,5],[8,9,3,1,3],[3,5,6,7,8],[7,8,3,2,1],[2,9,1,3,4]])
np.flip(u)

array([[4, 3, 1, 9, 2],
       [1, 2, 3, 8, 7],
       [8, 7, 6, 5, 3],
       [3, 1, 3, 9, 8],
       [5, 6, 9, 8, 7]])

In [104]:
# where() search values inside the array
f = np.array([1,2,3,4,5,6,7,8,9])
np.where(f%2==1)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [105]:
f = np.array([1,2,3,4,5,6,7,8,9])
np.where(f%2==0)

(array([1, 3, 5, 7], dtype=int64),)

In [107]:
h = np.array([4,7,8,9,4,6])
np.where(h*2==8)

(array([0, 4], dtype=int64),)

In [116]:
d = np.array([5,10,15,20,25,30,34,89,67])
np.where(d*5==25)

(array([0], dtype=int64),)

In [126]:
y = np.array([4,5,6,7,8,9,10,11,12])
np.where(y%2==2)

(array([], dtype=int64),)